---
title: "__Experiment 3:__ Data exploration"
author: "Massimiliano Canzi | `massimiliano.canzi@uni-konstanz.de`"
date: "27/03/2019; last modified 20/02/2021"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r, message = FALSE}
library(ggpubr)
library(devtools)
library(tidyverse)
library(ERP)
library(viridis)
library(akima)
library(scales)
library(reshape2)
library(lmerTest)
library(lme4)
```

```{r, include = F}
matplotlibRdBu_r <- colorRampPalette(c("#053061","#4694C4","#F6F6F6","#E7886C","#67001F"),interpolate = "spline")

loc_path <- "https://raw.githubusercontent.com/craddm/ExploringERPs/master/biosemi70elecs.loc"

ERP_123 = c("steelblue", "palevioletred1", "limegreen")
sign_col <- "indianred"
ERP_CTB = c("skyblue4", "palegreen3")
ERP_TTB = c("palevioletred1", "palegreen3")
```

## `readr` 

```{r, message = FALSE}
ERP <- rbind(read.csv("../data/EXP3.csv"), read.csv("../data/EXP2.csv")) %>%
            filter_if(~is.numeric(.), all_vars(!is.infinite(.))) %>%
  filter_if(~is.numeric(.), all_vars(!is.infinite(.))) %>%
  filter(time >= -100 | time <= 800) %>% 
  gather(electrode, amplitude, Fp1:T8, factor_key = TRUE) %>%
  mutate(time = as.numeric(as.character(format(round(time, 0), nsmall = 0))),
         Subj = as.factor(Subj),
         Block = as.factor(Block))

names(ERP) <- c("subject", "block", "condition", "time", "electrode", "amplitude")
```

```{r, message = FALSE}
electrodeLocs <- read_delim(loc_path, "\t",
  escape_double = FALSE,
  col_names = c("chanNo","theta","radius", "electrode"),
  trim_ws = TRUE)

ERP <- ERP %>% 
  mutate(time = as.factor(time)) %>%
  group_by(subject, block, condition, electrode, time) %>% 
  summarise(amplitude.mean = mean(amplitude),) %>% 
  ungroup() %>%
  mutate(time = as.numeric(as.character(time)))

ERP_testing <- ERP %>%
  mutate(time = as.double(time), 
         amplitude.mean = as.double(amplitude.mean))

electrodeLocs <- electrodeLocs %>%
  mutate(radianTheta = pi / 180 * theta,
          x = radius * sin(radianTheta), y = radius * cos(radianTheta))

ERP <- ERP %>% left_join(electrodeLocs, by = "electrode") %>%
  mutate(amplitude.mean = as.numeric(amplitude.mean), 
         electrode = as.factor(electrode)) %>%
  filter(amplitude.mean <= 20 & amplitude.mean >= -20) %>%
  mutate(amplitude.mean = as.numeric(format(round(amplitude.mean, 2), nsmall = 2)))
```

```{r, include = F}
ERP_CT <- filter(ERP_testing, block == "SINE") %>% 
  filter(condition != "first_syllable") %>% 
  filter(condition != "second_syllable") %>%
  filter(condition != "third_syllable") 

ERP_2CTest <- filter(ERP_testing, block == "ATT") %>%
  filter(condition != "first_syllable") %>% 
  filter(condition != "second_syllable") %>%
  filter(condition != "third_syllable")

ERP_CTest <- filter(ERP_testing, block == "SINE") %>%
  filter(condition != "first_syllable") %>% 
  filter(condition != "second_syllable") %>%
  filter(condition != "third_syllable") 

ERP_1CT <- filter(ERP_testing, block == "SINE") %>%
  filter(condition != "second_syllable") %>% 
  filter(condition != "third_syllable") 

ERP_S <- filter(ERP_testing, block == "SINE") %>%
  filter(condition != "control") %>%
  filter(condition != "target") 

ERP_S12 <- filter(ERP_testing, block == "SINE") %>%
  filter(condition != "third_syllable") %>%
  filter(condition != "control") %>%
  filter(condition != "target")

ERP_SS <- filter(ERP_testing, condition == "first_syllable")

ERP_EXP23 <- filter(ERP_testing, block == "SINE" | block == "ATT") %>%
  filter(condition == "target")
```

## plotting function: `significance`

```{r}
significance <- function(t = "CT", elec = "") {
  
  if (t == "CT") {
  
    ERP_testelec <- filter(ERP_CTest, electrode == elec)
    ERP_testwide <- spread(ERP_CTest, time, amplitude.mean)
    
    TERP <- ERP_testwide[(ERP_testwide$electrode == elec), 5:ncol(ERP_testwide)]
    cov.TERP = ERP_testwide[(ERP_testwide$electrode == elec), 1:4]
    cov.TERP = droplevels(cov.TERP)
    design <- model.matrix(~C(subject,sum) + condition, data = cov.TERP)
    design0 <- model.matrix(~C(subject,sum), data = cov.TERP) }
  
  else if (t == "S") {
    
    ERP_testelec <- filter(ERP_S12, electrode == elec)
    ERP_testwide <- spread(ERP_S12, time, amplitude.mean)
  
    TERP <- ERP_testwide[(ERP_testwide$electrode == elec), 5:ncol(ERP_testwide)]
    cov.TERP = ERP_testwide[(ERP_testwide$electrode == elec), 1:4]
    cov.TERP = droplevels(cov.TERP)
    design <- model.matrix(~C(subject,sum) + condition, data = cov.TERP)
    design0 <- model.matrix(~C(subject,sum), data = cov.TERP) }
  
  else if (t == "SS") {
    
    ERP_testelec <- filter(ERP_SS, electrode == elec)
    ERP_testwide <- spread(ERP_SS, time, amplitude.mean)
  
    TERP <- ERP_testwide[(ERP_testwide$electrode == elec), 5:ncol(ERP_testwide)]
    cov.TERP = ERP_testwide[(ERP_testwide$electrode == elec), 1:4]
    cov.TERP = droplevels(cov.TERP)
    design <- model.matrix(~C(subject,sum) + block, data = cov.TERP)
    design0 <- model.matrix(~C(subject,sum), data = cov.TERP) }
  
  else if (t == "EXP23") {
    
    ERP_testelec <- filter(ERP_EXP23, electrode == elec)
    ERP_testwide <- spread(ERP_EXP23, time, amplitude.mean)
  
    TERP <- ERP_testwide[(ERP_testwide$electrode == elec), 5:ncol(ERP_testwide)]
    cov.TERP = ERP_testwide[(ERP_testwide$electrode == elec), 1:4]
    cov.TERP = droplevels(cov.TERP)
    design <- model.matrix(~C(subject,sum) + block, data = cov.TERP)
    design0 <- model.matrix(~C(subject,sum), data = cov.TERP) }

  fabh <- erpfatest(TERP, design, design0, nbf = 6) 
  
  return(fabh$significant) }
```

## plotting function: `plot.diff`

```{r, message = F, warning = F}
plot.diff <- function(elec = "Cz", labels = FALSE) {
    ERP.new <- ERP %>% 
    filter(electrode == elec) %>%
    filter(block == "SINE") %>% 
    filter(condition == "control" | condition == "target")
    
    ERP.match <- ERP.new %>% filter(condition == "control") %>% filter(subject != "210")
    ERP.mism <- ERP.new %>% filter(condition == "target") %>% filter(subject != "210")
    
    ERP.diff <- ERP.match %>% 
      mutate(amplitude.mean = ERP.mism$amplitude.mean - ERP.match$amplitude.mean,
             condition = "difference")
    
    ERP.new <- bind_rows(ERP.new, ERP.diff)

  my.plot <- ggplot(ERP.new, aes(time, amplitude.mean, color = condition, linetype = condition)) +
      geom_line(stat = "summary") +
      xlim(c(-100, 400)) +
      geom_vline(xintercept = 0, linetype = "dashed" ) +
      geom_hline(yintercept = 0, linetype = "dashed") +
      ggtitle(elec) + 
      scale_linetype_manual(values = c(2, 1, 2), guide = F) +
      scale_color_manual(values = c("steelblue", "black", "indianred3"), name = "", labels = c("Match", "Difference", "Mismatch")) +
      theme(plot.title = element_text(size = 11, face = "bold")) 

  if (labels == TRUE) { 
    my.plot <- my.plot + 
      labs(x = "Time (ms)", y = expression(paste("Amplitude (", mu, "V)")), colour = "") +
      theme_minimal() } 

  if (labels == FALSE) {
    my.plot <- my.plot +
    labs(x = "", y = "", colour = "") +
    theme_void() }
  
  return(my.plot) }
```

```{r, message = F}
library(gganimate)
library(gifski)
```

```{r, message = F}
plot.diff() + transition_reveal(time)
```

```{r, eval = F, include = F}
af.diff <- ggarrange(
  plot.diff(elec = "Fp1", labels = TRUE),
  plot.diff(elec = "Fpz"),
  plot.diff(elec = "Fp2"),
  plot.diff(elec = "AF3",),
  plot.diff(elec = "AFz"),
  plot.diff(elec = "AF4"),
  plot.diff(elec = "F3"),
  plot.diff(elec = "Fz"),
  plot.diff(elec = "F4"),
  nrow = 3, ncol = 3,
  common.legend =  TRUE)

ggsave("./pictures/AFDIFF_Exp3.png", af.diff, width = 9, height = 7, dpi = "print")

fc.diff <- ggarrange( 
  plot.diff(elec = "FC3", labels = TRUE),
  plot.diff(elec = "FCz"),
  plot.diff(elec = "FC4"),
  plot.diff(elec = "C3"),
  plot.diff(elec = "Cz"),
  plot.diff(elec = "C4"),
  plot.diff(elec = "P3"),
  plot.diff(elec = "Pz"),
  plot.diff(elec = "P4"),
  nrow = 3, ncol = 3,
  common.legend =  TRUE)

ggsave("./pictures/FCDIFF_Exp3.png", fc.diff, width = 9, height = 7, dpi = "print")
```

## plotting function: `bae`

```{r}
bae <- function(elec = "Cz", type = "CT", labels = FALSE, range = "PMN", significant = TRUE) {
  
  if (range == "PMN") {
    xfocus <- c(-100, 400) }
  else if (range == "P600") {
    xfocus <- c(-100, 700) }
  
  if (type == "CT") {
    ERP_gae <- filter(ERP_CTest, electrode == elec) 
    colz <- c("steelblue", "indianred3")
    linez <- c(2, 1)
    labelz <- c("Match", "Mismatch")
    ind_v <- ERP_gae$condition }
  
  else if (type == "2CT") {
    ERP_gae <- filter(ERP_2CTest, electrode == elec) 
    colz <- c("steelblue", "indianred3")
    linez <- c(2, 1)
    labelz <- c("Match", "Mismatch")
    ind_v <- ERP_gae$condition }
  
  else if (type == "S") {
    ERP_gae <- filter(ERP_S, electrode == elec) 
    colz <- c("violetred3", "palegreen4", "mediumorchid4")
    linez <- c(1, 1, 1)
    labelz <- c("First tone", "Second tone", "Third tone")
    ind_v <- ERP_gae$condition }
  
  else if (type == "SS") {
    ERP_gae <- filter(ERP_SS, electrode == elec)
    colz <- c("steelblue", "indianred3")
    linez <- c(2, 1)
    labelz <- c("Syllable", "Tone")
    ind_v <- ERP_gae$block }
  
  else if (type == "1CT") {
    ERP_gae <- filter(ERP_1CT, electrode == elec) 
    colz <- c("steelblue", "palegreen4", "indianred2")
    linez <- c(2, 3, 1)
    labelz <- c("Match", "First tone", "Mismatch") 
    ind_v <- ERP_gae$condition }
  
  else if (type == "EXP23") {
    ERP_gae <- filter(ERP_EXP23, electrode == elec)
    colz <- c("steelblue", "indianred2")
    linez <- c(2, 1)
    labelz <- c("Experiment 2", "Experiment 3")
    ind_v <- ERP_gae$block }

    gap <- ggplot(ERP_gae, aes(time, amplitude.mean, colour = ind_v)) +
      geom_line(stat = "summary") +
      xlim(xfocus) +
      geom_vline(xintercept = 0, linetype = "dashed" ) +
      geom_hline(yintercept = 0, linetype = "dashed") +
      scale_colour_manual(values = colz, name = "", labels = labelz) +
      ggtitle(elec) +
      theme(plot.title = element_text(size = 11, face = "bold")) 
  
  if (labels == TRUE) {
    gap <- gap +
      labs(x = "Time (ms)", y = expression(paste("Amplitude (", mu, "V)")), colour = "") +
      theme_minimal() }
    
  if (labels == FALSE) {
    gap <- gap + 
      labs(x = "", y = "", colour = "") +
      theme_void() }
  
  if (significant == TRUE) {
    spts <- significance(t = type, elec) 
    spts1 <- as.data.frame(spts)
    
    if (length(spts) != 0) {
      gap = gap + geom_point(data = spts1, mapping = aes(x = spts, y = -0.3), size = 3, shape = 20, 
      color = sign_col) } }
  
  return(gap) }
```

```{r, message = F}
bae(significant = FALSE, labels = FALSE) + transition_reveal(time)
```

```{r, eval = F, include = F}
anterior_frontal3 <- ggarrange(
  bae(elec = "Fp1", labels = TRUE),
  bae(elec = "Fpz"),
  bae(elec = "Fp2"),
  bae(elec = "AF3"),
  bae(elec = "AFz"),
  bae(elec = "AF4"),
  bae(elec = "F3"),
  bae(elec = "Fz"),
  bae(elec = "F4"),
  nrow = 3, ncol = 3,
  common.legend =  TRUE)

ggsave("./pictures/P3_Exp3.png", anterior_frontal3, width = 9, height = 7, dpi = "print")

fronto_central3 <- ggarrange( 
  bae(elec = "FC3", labels = TRUE),
  bae(elec = "FCz"),
  bae(elec = "FC4"),
  bae(elec = "C3"),
  bae(elec = "Cz"),
  bae(elec = "C4"),
  bae(elec = "P3"),
  bae(elec = "Pz"),
  bae(elec = "P3"),
  nrow = 3, ncol = 3,
  common.legend =  TRUE)

ggsave("./pictures/P4_Exp3.png", fronto_central3, width = 9, height = 7, dpi = "print")
```

```{r, eval = F, include = F}
noafa123_af3 <- ggarrange(
  bae(elec = "Fp1", type = "S", labels = TRUE, significant = FALSE),
  bae(elec = "Fpz", type = "S", significant = FALSE),
  bae(elec = "Fp2", type = "S", significant = FALSE),
  bae(elec = "AF3", type = "S", significant = FALSE),
  bae(elec = "AFz", type = "S", significant = FALSE),
  bae(elec = "AF4", type = "S", significant = FALSE),
  bae(elec = "F3", type = "S", significant = FALSE),
  bae(elec = "Fz", type = "S", significant = FALSE),
  bae(elec = "F4", type = "S", significant = FALSE),
  nrow = 3, ncol = 3, 
  common.legend =  TRUE)

ggsave("./pictures/P5_Exp3.png", noafa123_af3, width = 9, height = 7, dpi = "print")

bae(elec = "F4", type = "CT", labels = TRUE, significant = FALSE)

noafa123_fc3 <- ggarrange(
  bae(elec = "FC3", type = "S", labels = TRUE, significant = FALSE),
  bae(elec = "FCz", type = "S", significant = FALSE),
  bae(elec = "FC4", type = "S", significant = FALSE),
  bae(elec = "F3", type = "S", significant = FALSE),
  bae(elec = "Fz", type = "S", significant = FALSE),
  bae(elec = "F4", type = "S", significant = FALSE),
  bae(elec = "P3", type = "S", significant = FALSE),
  bae(elec = "Pz", type = "S", significant = FALSE),
  bae(elec = "P4", type = "S", significant = FALSE),
  nrow = 3, ncol = 3, 
  common.legend =  TRUE)

ggsave("./pictures/P6_Exp3.png", noafa123_fc3, width = 9, height = 7, dpi = "print")

anterior_frontal1233 <- ggarrange(
  bae(elec = "Fp1", type = "S", labels = TRUE),
  bae(elec = "Fpz", type = "S"),
  bae(elec = "Fp2", type = "S"),
  bae(elec = "AF3", type = "S"),
  bae(elec = "AFz", type = "S"),
  bae(elec = "AF4", type = "S"),
  bae(elec = "F3", type = "S"),
  bae(elec = "Fz", type = "S"),
  bae(elec = "F4", type = "S"), 
  nrow = 3, ncol = 3,
  common.legend =  TRUE)

ggsave("./pictures/P7_Exp3.png", anterior_frontal1233, width = 9, height = 7, dpi = "print")

fronto_central1233 <- ggarrange( 
  bae(elec = "FC3", type = "S", labels = TRUE),
  bae(elec = "FCz", type = "S"),
  bae(elec = "FC4", type = "S"),
  bae(elec = "C3", type = "S"),
  bae(elec = "Cz", type = "S"),
  bae(elec = "C4", type = "S"),
  bae(elec = "P3", type = "S"),
  bae(elec = "Pz", type = "S"),
  bae(elec = "P4", type = "S"),
  nrow = 3, ncol = 3,
  common.legend =  TRUE)

ggsave("./pictures/P8_Exp3.png", fronto_central1233, width = 9, height = 7, dpi = "print")
```

```{r, eval = F, include = F}
ssaf <- ggarrange(
  bae(elec = "Fp1", type = "SS", labels = TRUE, significant = FALSE),
  bae(elec = "Fpz", type = "SS", significant = FALSE),
  bae(elec = "Fp2", type = "SS", significant = FALSE),
  bae(elec = "AF3", type = "SS", significant = FALSE),
  bae(elec = "AFz", type = "SS", significant = FALSE),
  bae(elec = "AF4", type = "SS", significant = FALSE),
  bae(elec = "F3", type = "SS", significant = FALSE),
  bae(elec = "Fz", type = "SS", significant = FALSE),
  bae(elec = "F4", type = "SS", significant = FALSE),
  nrow = 3, ncol = 3, 
  common.legend =  TRUE)

ggsave("./pictures/P9_Exp3.png", ssaf, width = 9, height = 7, dpi = "print")

ssfc <- ggarrange(
  bae(elec = "FC3", type = "SS", labels = TRUE, significant = FALSE),
  bae(elec = "FCz", type = "SS", significant = FALSE),
  bae(elec = "FC4", type = "SS", significant = FALSE),
  bae(elec = "C3", type = "SS", significant = FALSE),
  bae(elec = "Cz", type = "SS", significant = FALSE),
  bae(elec = "C4", type = "SS", significant = FALSE),
  bae(elec = "P3", type = "SS", significant = FALSE),
  bae(elec = "Pz", type = "SS", significant = FALSE),
  bae(elec = "P4", type = "SS", significant = FALSE),
  nrow = 3, ncol = 3, 
  common.legend =  TRUE)

ggsave("./pictures/P10_Exp3.png", ssfc, width = 9, height = 7, dpi = "print")
```

```{r, eval = F, include = F}
noafa1CT_af3 <- ggarrange(
  bae(elec = "Fp1", type = "1CT", labels = TRUE, significant = FALSE),
  bae(elec = "Fpz", type = "1CT", significant = FALSE),
  bae(elec = "Fp2", type = "1CT", significant = FALSE),
  bae(elec = "AF3", type = "1CT", significant = FALSE),
  bae(elec = "AFz", type = "1CT", significant = FALSE),
  bae(elec = "AF4", type = "1CT", significant = FALSE),
  bae(elec = "F3", type = "1CT", significant = FALSE),
  bae(elec = "Fz", type = "1CT", significant = FALSE),
  bae(elec = "F4", type = "1CT", significant = FALSE),
  nrow = 3, ncol = 3, 
  common.legend =  TRUE)

ggsave("./pictures/P13_Exp3.png", noafa1CT_af3, width = 11, height = 9, dpi = "print")

noafa1CT_fc3 <- ggarrange(
  bae(elec = "FC3", type = "1CT", labels = TRUE, significant = FALSE),
  bae(elec = "FCz", type = "1CT", significant = FALSE),
  bae(elec = "FC4", type = "1CT", significant = FALSE),
  bae(elec = "C3", type = "1CT", significant = FALSE),
  bae(elec = "Cz", type = "1CT", significant = FALSE),
  bae(elec = "C4", type = "1CT", significant = FALSE),
  bae(elec = "P3", type = "1CT", significant = FALSE),
  bae(elec = "Pz", type = "1CT", significant = FALSE),
  bae(elec = "P4", type = "1CT", significant = FALSE),
  nrow = 3, ncol = 3, 
  common.legend =  TRUE)

ggsave("./pictures/P14_Exp3.png", noafa1CT_fc3, width = 11, height = 9, dpi = "print")
```

```{r, eval = F, include = F}
exp23anterior_frontal <- ggarrange(
  bae(elec = "Fp1", type = "EXP23", labels = TRUE, significant = FALSE),
  bae(elec = "Fpz", type = "EXP23", significant = FALSE),
  bae(elec = "Fp2", type = "EXP23", significant = FALSE),
  bae(elec = "AF3", type = "EXP23", significant = FALSE),
  bae(elec = "AFz", type = "EXP23", significant = FALSE),
  bae(elec = "AF4", type = "EXP23", significant = FALSE),
  bae(elec = "F3", type = "EXP23", significant = FALSE),
  bae(elec = "Fz", type = "EXP23", significant = FALSE),
  bae(elec = "F4", type = "EXP23", significant = FALSE),
  nrow = 3, ncol = 3, 
  common.legend =  TRUE)

ggsave("./pictures/P11_Exp3.png", exp23anterior_frontal, width = 9, height = 7, dpi = "print")

exp23fronto_central <- ggarrange(
  bae(elec = "FC3", type = "EXP23", labels = TRUE, significant = FALSE),
  bae(elec = "FCz", type = "EXP23", significant = FALSE),
  bae(elec = "FC4", type = "EXP23", significant = FALSE),
  bae(elec = "C3", type = "EXP23", significant = FALSE),
  bae(elec = "Cz", type = "EXP23", significant = FALSE),
  bae(elec = "C4", type = "EXP23", significant = FALSE),
  bae(elec = "P3", type = "EXP23", significant = FALSE),
  bae(elec = "Pz", type = "EXP23", significant = FALSE),
  bae(elec = "P4", type = "EXP23", significant = FALSE),
  nrow = 3, ncol = 3, 
  common.legend =  TRUE)

ggsave("./pictures/P12_Exp3.png", exp23fronto_central, width = 9, height = 7, dpi = "print")
```

## plotting function `theme_topo` by __craddm__

```{r}
theme_topo <- function(base_size = 12)
  {theme_bw(base_size = base_size) %+replace% theme(rect = element_blank(), line = element_blank(), axis.text = element_blank(), axis.title = element_blank())}

circleFun <- function(center = c(0,0), diameter = 1, npoints = 100) {
  r = diameter / 2
  tt <- seq(0,2 * pi, length.out = npoints)
  xx <- center[1] + r * cos(tt)
  yy <- center[2] + r * sin(tt)
  return(data.frame(x = xx, y = yy)) }

headShape <- circleFun(c(0, 0), round(max(electrodeLocs$x)), npoints = 100) 
nose <- data.frame(x = c(-0.075, 0, .075), y=c(.495, .575, .495))
```

## plotting function: `int_scalp_plot`

```{r}
int_scalp_plot <- function(TP1, TP2, cond = "control") {
  
  ERP_lme <- filter(ERP, time >= TP1) %>%
    filter(time <= TP2) %>%
    filter(block == "SINE")

  ERP_lme <- ERP_lme %>% group_by(subject, block, condition, electrode) %>%
    summarise(avg.mean = mean(amplitude.mean),) %>%
    ungroup
  
  ERP_lme <- filter(ERP_lme, condition == cond)
  gridRes <- 124
  
  electrodeLocs <- read_delim("https://raw.githubusercontent.com/craddm/ExploringERPs/master/biosemi70elecs.loc", "\t",
  escape_double = FALSE,
  col_names = c("chanNo","theta","radius", "electrode"),
  trim_ws = TRUE)
  
  electrodeLocs$radianTheta <- pi/180*electrodeLocs$theta
  electrodeLocs <- electrodeLocs %>%
  mutate(x = .$radius*sin(.$radianTheta), y = .$radius*cos(.$radianTheta))

  singleTimepoint <- ERP_lme %>% left_join(electrodeLocs, by = "electrode")

  singleTimepoint$Amplitude <- singleTimepoint$avg.mean
  
  tmpTopo <- with(singleTimepoint, interp(x = x, y = y, z = Amplitude, xo = seq(min(x)*2, max(x)*2, length = gridRes), yo = seq(min(y)*2, max(y)*2, length = gridRes), linear = FALSE, extrap = TRUE, duplicate = TRUE))

  interpTopo <- data.frame(x = tmpTopo$x, tmpTopo$z)
  names(interpTopo)[1:length(tmpTopo$y)+1] <- tmpTopo$y
  interpTopo <- gather(interpTopo, key = y, value = Amplitude, -x, convert = TRUE)
  interpTopo$incircle <- sqrt(interpTopo$x^2 + interpTopo$y^2) < .7 
  interpTopo <- interpTopo[interpTopo$incircle,] 
  maskRing <- circleFun(diameter = 1.42) 

  ScalpPlotT <- ggplot(interpTopo, aes(x = x, y = y, fill = Amplitude)) +
    geom_raster() +
    stat_contour(aes(z = Amplitude, linetype = ..level..<0), colour = "black", size = 0.8, show.legend = FALSE) +
    theme_topo() +
    scale_fill_viridis(option = "viridis", limits = c(-1, 3), guide = "colorbar", oob = squish) +
    geom_path(data = maskRing, aes(x, y, z = NULL, fill =NULL), colour = "white", size = 6) +
    geom_point(data = singleTimepoint, aes(x, y), size = 1) +
    geom_path(data = headShape, aes(x, y, z = NULL, fill = NULL), size = 1.5) +
    geom_path(data = nose, aes(x, y, z = NULL, fill = NULL), size = 1.5) +
    #ggtitle(paste0(cond)) +
    coord_fixed() +
    theme(plot.title = element_text(hjust = 0.5, lineheight = 0.5))
  return(ScalpPlotT) }

int_compare_scalps <- function(tp1, tp2) {
  control_map <- int_scalp_plot(TP1 = tp1, TP2 = tp2, cond = "control") 
  target_map <- int_scalp_plot(TP1 = tp1, TP2 = tp2, cond = "target")

final_plot <- ggarrange(
  target_map + ggtitle("Mismatch"),
  control_map + ggtitle("Match"),
  common.legend = TRUE)

return(final_plot) }
```

```{r, message = F, warning = F}
x <- int_compare_scalps(20, 40)
```

```{r, echo = F}
x
```

```{r, include = F, eval = FALSE}
n1 <- int_compare_scalps(80, 120)
ggsave("./pictures/scalp_n1.png", n1, width = 9, height = 5, dpi = "print")

mmn <- int_compare_scalps(150, 200)
ggsave("./pictures/scalp_MMN.png", mmn, width = 9, height = 5, dpi = "print")

P3 <- int_compare_scalps(225, 250)
ggsave("./pictures/scalp_P3.png", P3, width = 9, height = 5, dpi = "print")

pmn <- int_compare_scalps(290, 310)
ggsave("./pictures/scalp_pmn.png", pmn, width = 9, height = 5, dpi = "print")

p600 <- int_compare_scalps(575, 625)
ggsave("./pictures/scalp_P600.png", p600, width = 9, height = 5, dpi = "print")
```

